[package]
name = "dyn-prog"
version = "0.1.0"
authors = ["hardkey <adam.shimi@toulouse-inp.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
